(() => {
  "use strict";
  const $ = (selector) => document.querySelector(selector);
  const canvas = $("#gridCanvas"), ctx = canvas.getContext("2d");
  const controls = { run: $("#runButton"), speed: $("#speedRange"), density: $("#densityRange"), clear: $("#clearButton"), clearPath: $("#clearPathButton"), maze: $("#mazeButton") };
  const metrics = { explored: $("#exploredMetric"), route: $("#routeMetric"), frontier: $("#frontierMetric"), time: $("#timeMetric") };
  const colors = { base: "#0b1428", wall: "#31466a", start: "#36e0da", end: "#ff5f6d", visited: "#2767c2", frontier: "#5b57da", path: "#ffd667" };
  const state = { cols: 24, rows: 15, walls: new Set(), start: { x: 3, y: 7 }, end: { x: 20, y: 7 }, tool: "wall", algorithm: "astar", speed: 3, visited: [], frontier: [], path: [], running: false, timer: 0, feed: [] };
  class MinHeap { constructor(){ this.data=[]; } push(item){this.data.push(item);this.up(this.data.length-1);} pop(){if(!this.data.length)return null;const top=this.data[0],last=this.data.pop();if(this.data.length){this.data[0]=last;this.down(0);}return top;} get size(){return this.data.length;} up(i){while(i){const p=(i-1)>>1;if(this.data[p].priority<=this.data[i].priority)break;[this.data[p],this.data[i]]=[this.data[i],this.data[p]];i=p;}} down(i){for(;;){let l=i*2+1,r=l+1,b=i;if(l<this.data.length&&this.data[l].priority<this.data[b].priority)b=l;if(r<this.data.length&&this.data[r].priority<this.data[b].priority)b=r;if(b===i)return;[this.data[b],this.data[i]]=[this.data[i],this.data[b]];i=b;}} }
  const keyOf=(x,y)=>`${x},${y}`, pointFromKey=(key)=>{const[x,y]=key.split(",").map(Number);return{x,y};}, same=(a,b)=>a.x===b.x&&a.y===b.y, manhattan=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
  const neighbors=(node)=>[[1,0],[-1,0],[0,1],[0,-1]].map(([x,y])=>({x:node.x+x,y:node.y+y})).filter(p=>p.x>=0&&p.y>=0&&p.x<state.cols&&p.y<state.rows&&!state.walls.has(keyOf(p.x,p.y)));
  const graph=()=>{const list=new Map();for(let y=0;y<state.rows;y++)for(let x=0;x<state.cols;x++)if(!state.walls.has(keyOf(x,y)))list.set(keyOf(x,y),neighbors({x,y}));return list;};
  function runSearch(){const started=performance.now(),map=graph(),open=new MinHeap(),startKey=keyOf(state.start.x,state.start.y),endKey=keyOf(state.end.x,state.end.y),dist=new Map([[startKey,0]]),parent=new Map(),closed=new Set(),order=[],frontier=[];open.push({key:startKey,priority:state.algorithm==="astar"?manhattan(state.start,state.end):0});while(open.size){const current=open.pop(),currentKey=current.key;if(closed.has(currentKey))continue;closed.add(currentKey);order.push(pointFromKey(currentKey));if(currentKey===endKey)break;for(const next of map.get(currentKey)||[]){const nextKey=keyOf(next.x,next.y),tentative=dist.get(currentKey)+1;if(tentative<(dist.get(nextKey)??Infinity)){dist.set(nextKey,tentative);parent.set(nextKey,currentKey);const estimate=state.algorithm==="astar"?manhattan(next,state.end):0;open.push({key:nextKey,priority:tentative+estimate});frontier.push(next);}}}const path=[];if(parent.has(endKey)||startKey===endKey){let cursor=endKey;while(cursor){path.unshift(pointFromKey(cursor));if(cursor===startKey)break;cursor=parent.get(cursor);}}return{order,frontier,path,elapsed:performance.now()-started,maxFrontier:frontier.length};}
  function resize(){const rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);draw();}function cellMetrics(){const rect=canvas.getBoundingClientRect();return{w:rect.width/state.cols,h:rect.height/state.rows};}
  function draw(){const rect=canvas.getBoundingClientRect(),{w,h}=cellMetrics();ctx.clearRect(0,0,rect.width,rect.height);ctx.fillStyle=colors.base;ctx.fillRect(0,0,rect.width,rect.height);const set=(items)=>new Set(items.map(p=>keyOf(p.x,p.y))),visited=set(state.visited),frontier=set(state.frontier),path=set(state.path);for(let y=0;y<state.rows;y++)for(let x=0;x<state.cols;x++){const k=keyOf(x,y),px=x*w,py=y*h;let fill=colors.base;if(state.walls.has(k))fill=colors.wall;else if(visited.has(k))fill=colors.visited;else if(frontier.has(k))fill=colors.frontier;else if(path.has(k))fill=colors.path;ctx.fillStyle=fill;ctx.fillRect(px+1,py+1,w-2,h-2);}drawMarker(state.start,w,h,colors.start,"A");drawMarker(state.end,w,h,colors.end,"B");}
  function drawMarker(point,w,h,color,label){const x=(point.x+.5)*w,y=(point.y+.5)*h,r=Math.min(w,h)*.27;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=14;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#07101f";ctx.font=`800 ${Math.max(9,r)}px system-ui`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(label,x,y+.5);}
  function clearSearch(){clearTimeout(state.timer);state.running=false;state.visited=[];state.frontier=[];state.path=[];state.feed=[];updateMetrics();renderFeed();setStatus("Ready to explore","Set your course");controls.run.disabled=false;draw();}
  function animate(result){clearSearch();state.running=true;controls.run.disabled=true;setStatus("Searching map","Exploring intersections");const total=result.order.length,speed=[27,15,8,2][state.speed-1],chunk=Math.max(1,Math.ceil(total/120));let i=0;const tick=()=>{const end=Math.min(total,i+chunk);state.visited.push(...result.order.slice(i,end));state.frontier=result.frontier.slice(Math.max(0,end-25),end);i=end;updateMetrics({explored:i,frontier:Math.min(result.maxFrontier,25)});if(i%Math.max(chunk*8,1)===0)addFeed(`scanning junction ${i} of ${total}`);draw();if(i<total){state.timer=setTimeout(tick,speed);}else{state.frontier=[];state.path=result.path;state.running=false;controls.run.disabled=false;const found=result.path.length>0;updateMetrics({explored:total,frontier:result.maxFrontier,route:found?result.path.length-1:"—",time:result.elapsed});addFeed(found?`route locked · ${result.path.length-1} steps`:"no traversable route found");setStatus(found?"Route found":"No route available",found?`${result.path.length-1} steps to destination`:"Clear barriers and retry");draw();}};tick();}
  function updateMetrics(values={}){metrics.explored.textContent=values.explored??state.visited.length;metrics.frontier.textContent=values.frontier??state.frontier.length;metrics.route.textContent=values.route??(state.path.length?state.path.length-1:"—");metrics.time.textContent=values.time===undefined?(state.running?"…":"0 ms"):`${Math.max(0,values.time).toFixed(values.time<1?2:1)} ms`;}
  function setStatus(title,subtitle){const el=$("#statusPill");el.querySelector("strong").textContent=title;el.querySelector("small").textContent=subtitle;}function addFeed(message){state.feed.unshift(message);state.feed=state.feed.slice(0,7);renderFeed();}function renderFeed(){const list=$("#searchFeed");if(!state.feed.length){list.innerHTML='<li class="empty-feed">Search activity will appear here.</li>';return;}list.innerHTML=state.feed.map((m,i)=>`<li><span>${String(i+1).padStart(2,"0")}</span> ${m}</li>`).join("");}
  function setTool(tool){state.tool=tool;document.querySelectorAll(".tool").forEach(btn=>{const active=btn.dataset.tool===tool;btn.classList.toggle("active",active);btn.setAttribute("aria-pressed",active);});}function setAlgorithm(algorithm){state.algorithm=algorithm;document.querySelectorAll(".algorithm").forEach(btn=>{const active=btn.dataset.algorithm===algorithm;btn.classList.toggle("active",active);btn.setAttribute("aria-pressed",active);});const astar=algorithm==="astar";$("#algorithmBadge").textContent=astar?"A* SEARCH":"DIJKSTRA";$("#explanationTitle").textContent=astar?"A* Search":"Dijkstra's Algorithm";$("#explanationText").textContent=astar?"A* prioritizes nodes using the known travel cost and an estimate of the remaining distance. It usually reaches the goal with fewer explored nodes.":"Dijkstra expands the lowest-cost frontier first. On this uniform grid, it guarantees a shortest route without using a destination heuristic.";$("#formula").textContent=astar?"f(n) = g(n) + h(n)":"next = node with smallest g(n)";clearSearch();}
  function pointAt(event){const rect=canvas.getBoundingClientRect(),{w,h}=cellMetrics();return{x:Math.max(0,Math.min(state.cols-1,Math.floor((event.clientX-rect.left)/w))),y:Math.max(0,Math.min(state.rows-1,Math.floor((event.clientY-rect.top)/h))) };}function paint(point){if(state.running)return;const k=keyOf(point.x,point.y);if(state.tool==="start"&&!same(point,state.end)){state.start=point;state.walls.delete(k);}else if(state.tool==="end"&&!same(point,state.start)){state.end=point;state.walls.delete(k);}else if(state.tool==="erase"){state.walls.delete(k);}else if(!same(point,state.start)&&!same(point,state.end)){state.walls.add(k);}clearSearch();draw();}
  function generateMaze(){clearSearch();state.walls.clear();for(let y=0;y<state.rows;y++)for(let x=0;x<state.cols;x++){const protectedCell=(x===state.start.x&&y===state.start.y)||(x===state.end.x&&y===state.end.y);if(!protectedCell&&Math.random()<.27)state.walls.add(keyOf(x,y));}addFeed("generated randomized street closures");draw();}function changeDensity(cols){state.cols=cols;state.rows=Math.max(10,Math.round(cols/1.6));state.start={x:Math.max(1,Math.round(state.cols*.14)),y:Math.floor(state.rows/2)};state.end={x:Math.min(state.cols-2,Math.round(state.cols*.84)),y:Math.floor(state.rows/2)};state.walls.clear();clearSearch();$("#densityValue").textContent=`${state.cols} × ${state.rows}`;$("#gridLabel").textContent=`${state.cols} × ${state.rows}`;addFeed(`resized to ${state.cols*state.rows} spatial nodes`);draw();}
  let painting=false;canvas.addEventListener("pointerdown",e=>{painting=true;canvas.setPointerCapture(e.pointerId);paint(pointAt(e));});canvas.addEventListener("pointermove",e=>{if(painting&&(state.tool==="wall"||state.tool==="erase"))paint(pointAt(e));});canvas.addEventListener("pointerup",()=>painting=false);canvas.addEventListener("pointerleave",()=>painting=false);document.querySelectorAll(".tool").forEach(btn=>btn.addEventListener("click",()=>setTool(btn.dataset.tool)));document.querySelectorAll(".algorithm").forEach(btn=>btn.addEventListener("click",()=>setAlgorithm(btn.dataset.algorithm)));controls.run.addEventListener("click",()=>animate(runSearch()));controls.clear.addEventListener("click",()=>{state.walls.clear();clearSearch();addFeed("cleared all barriers");draw();});controls.clearPath.addEventListener("click",clearSearch);controls.maze.addEventListener("click",generateMaze);$("#clearFeedButton").addEventListener("click",()=>{state.feed=[];renderFeed();});controls.speed.addEventListener("input",e=>{state.speed=Number(e.target.value);$("#speedValue").textContent=["Slow","Steady","Fast","Instant"][state.speed-1];});controls.density.addEventListener("input",e=>changeDensity(Number(e.target.value)));$("#helpButton").addEventListener("click",()=>$("#helpDialog").showModal());$("#closeHelp").addEventListener("click",()=>$("#helpDialog").close());document.addEventListener("keydown",e=>{if(e.target.matches("input"))return;const key=e.key.toLowerCase();if(key===" "){e.preventDefault();if(!state.running)animate(runSearch());}else if({w:"wall",e:"erase",s:"start",d:"end"}[key])setTool({w:"wall",e:"erase",s:"start",d:"end"}[key]);else if(key==="c")clearSearch();});window.addEventListener("resize",resize);resize();updateMetrics();
})();
